#check local up 
---

- hosts: all
  connection: local
  gather_facts: no
  
#  remote_user: ec2-user
#  become: yes

  tasks:
   - name: check status
     ping:

   - name: create new file
     file: path=/tmp/ansible/ran_ansible.txt state=touch
