#check local up 
---

- hosts: localop
  connection: local
  gather_facts: no

  tasks:
   - name: check status
     ping:

   - name: create new file
     file: path=/tmp/ran_ansible.txt state=touch
